FROM golang:1.10-alpine3.8

RUN apk add --no-cache curl git rpm

RUN go get -u github.com/golang/dep/cmd/dep

ARG GORELEASER_VERSION=v0.82.1

RUN curl -L -o goreleaser.tgz \
      https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz && \
      tar -zxvf goreleaser.tgz -C /usr/local/bin/ && \
      rm -f goreleaser.tgz

ENTRYPOINT [ "/usr/local/bin/goreleaser" ]
CMD [ "-h" ]
