FROM golang:1.22-alpine

MAINTAINER Conjur Inc

RUN apk add --no-cache bash \
                       build-base \
                       curl \
                       git \
                       jq \
                       less && \
    go install github.com/jstemmer/go-junit-report@latest && \
    go install github.com/axw/gocov/gocov@latest && \
    go install github.com/AlekSi/gocov-xml@latest && \
    mkdir -p /summon-conjur/output

WORKDIR /summon-conjur

COPY go.mod go.sum ./

COPY . .
RUN go build -o summon-conjur cmd/main.go

EXPOSE 8080
